In [1]:
import numpy as np
import pandas as pd
from sklearn import linear_model

# Data

In [42]:
df=pd.read_csv(r'hiring.csv')
df

  experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0        NaN                    8.0                           9      50000
1        NaN                    8.0                           6      45000
2       five                    6.0                           7      60000
3        two                   10.0                          10      65000
4      seven                    9.0                           6      70000
5      three                    7.0                          10      62000
6        ten                    NaN                           7      72000
7     eleven                    7.0                           8      80000

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 4 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   experience                  6 non-null      object
 1   test_score(out of 10)       7 non-null      float64
 2   interview_score(out of 10)  8 non-null      int64
 3   salary($)                   8 non-null      int64
dtypes: float64(1), int64(2), object(1)
memory usage: 388.0+ bytes

In [4]:
df.describe()

       test_score(out of 10)  interview_score(out of 10)    salary($)
count               7.000000                    8.000000      8.00000
mean                7.857143                    7.875000  63000.00000
std                 1.345185                    1.642081  11501.55269
min                 6.000000                    6.000000  45000.00000
25%                 7.000000                    6.750000  57500.00000
50%                 8.000000                    7.500000  63500.00000
75%                 8.500000                    9.250000  70500.00000
max                10.000000                   10.000000  80000.00000

In [5]:
! pip install word2number

Defaulting to user installation because normal site-packages is not writeable
Collecting word2number
  Downloading word2number-1.1.zip (9.7 kB)
  Preparing metadata (setup.py) ... done
Building wheels for collected packages: word2number
  Building wheel for word2number (setup.py) ... done
  Created wheel for word2number: filename=word2number-1.1-py3-none-any.whl size=5566 sha256=3e01a4d44d129d20e9df0175aeb57339bb299ed8f3a6c7355839b0c371d27a6a
  Stored in directory: /home/bala/.cache/pip/wheels/cd/ef/ae/073b491b14d25e2efafcffca9e16b2ee6d114ec5c643ba4f06
Successfully built word2number
Installing collected packages: word2number
Successfully installed word2number-1.1

In [43]:
from word2number import w2n
df.experience=df.experience.fillna('Zero')
df

  experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0       Zero                    8.0                           9      50000
1       Zero                    8.0                           6      45000
2       five                    6.0                           7      60000
3        two                   10.0                          10      65000
4      seven                    9.0                           6      70000
5      three                    7.0                          10      62000
6        ten                    NaN                           7      72000
7     eleven                    7.0                           8      80000

In [44]:
df.experience=df.experience.apply(w2n.word_to_num)
df

   experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0           0                    8.0                           9      50000
1           0                    8.0                           6      45000
2           5                    6.0                           7      60000
3           2                   10.0                          10      65000
4           7                    9.0                           6      70000
5           3                    7.0                          10      62000
6          10                    NaN                           7      72000
7          11                    7.0                           8      80000

In [46]:
# df['test_score(out of 10)']=df['test_score(out of 10)'].fillna(df['test_score(out of 10)'].mean)
import math
mean_val=math.floor(df['test_score(out of 10)'].mean())
mean_val

7

In [47]:
df['test_score(out of 10)']=df['test_score(out of 10)'].fillna(mean_val)
df

   experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0           0                    8.0                           9      50000
1           0                    8.0                           6      45000
2           5                    6.0                           7      60000
3           2                   10.0                          10      65000
4           7                    9.0                           6      70000
5           3                    7.0                          10      62000
6          10                    7.0                           7      72000
7          11                    7.0                           8      80000

In [48]:
model=linear_model.LinearRegression()
model.fit(df[['experience','test_score(out of 10)','interview_score(out of 10)']],df['salary($)'])

LinearRegression()

In [50]:
model.predict([[2,9,6]])

/home/bala/.local/lib/python3.11/site-packages/sklearn/base.py:493: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

array([53713.86677124])

In [51]:
model.predict([[3,4,2]])

/home/bala/.local/lib/python3.11/site-packages/sklearn/base.py:493: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

array([36939.66002285])